import { useEffect, useState } from 'react';
import { Alert, Card, CardContent, FormControl, Grid, InputLabel, MenuItem, Select, Table, TableBody, TableCell, TableHead, TableRow, Typography } from '@mui/material';
import VerifiedUserIcon from '@mui/icons-material/VerifiedUser';
import FactCheckIcon from '@mui/icons-material/FactCheck';
import ErrorIcon from '@mui/icons-material/Error';
import RuleIcon from '@mui/icons-material/Rule';
import PageHeader from '../components/PageHeader';
import { complianceApi } from '../services/api';
import AccentMetricCard from '../components/AccentMetricCard';

export default function CompliancePage() {
  const [frameworks, setFrameworks] = useState<any[]>([]); const [controls, setControls] = useState<any[]>([]); const [summary, setSummary] = useState<any>(null); const [selected, setSelected] = useState(''); const [error, setError] = useState<string | null>(null);
  useEffect(() => { complianceApi.getFrameworks().then((r) => { setFrameworks(r.data); if (r.data[0]) setSelected(r.data[0].id); }).catch((e) => setError(e.response?.data?.message || e.message)); }, []);
  useEffect(() => { if (!selected) return; Promise.all([complianceApi.getControls(selected), complianceApi.getSummary(selected)]).then(([c, s]) => { setControls(c.data); setSummary(s.data); }).catch((e) => setError(e.response?.data?.message || e.message)); }, [selected]);
  return <><PageHeader title="Compliance Dashboard" subtitle="Framework controls, evidence status, and assessment gaps" />{error && <Alert severity="error">{error}</Alert>}<FormControl sx={{ minWidth: 240, mb: 3 }}><InputLabel>Framework</InputLabel><Select label="Framework" value={selected} onChange={(e) => setSelected(e.target.value)}>{frameworks.map((framework) => <MenuItem key={framework.id} value={framework.id}>{framework.name} {framework.version || ''}</MenuItem>)}</Select></FormControl>{summary && <Grid container spacing={2} sx={{ mb: 3 }}><Grid item xs={12} sm={6} md={3}><AccentMetricCard label="Compliance" value={`${summary.percentage.toFixed(1)}%`} subtitle="Calculated assessment" color="#22C55E" icon={<VerifiedUserIcon />} /></Grid><Grid item xs={12} sm={6} md={3}><AccentMetricCard label="Controls" value={summary.controls} subtitle="Framework requirements" color="#38BDF8" icon={<RuleIcon />} /></Grid><Grid item xs={12} sm={6} md={3}><AccentMetricCard label="Compliant" value={summary.compliant} subtitle="Controls passing" color="#22C55E" icon={<FactCheckIcon />} /></Grid><Grid item xs={12} sm={6} md={3}><AccentMetricCard label="Gaps" value={summary.nonCompliant + summary.notAssessed} subtitle="Needs remediation or review" color="#EF4444" icon={<ErrorIcon />} /></Grid></Grid>}<Card sx={{ overflow: 'hidden', borderColor: '#334155' }}><Table><TableHead><TableRow sx={{ bgcolor: '#101827' }}><TableCell>Control</TableCell><TableCell>Title</TableCell><TableCell>Status</TableCell><TableCell>Owner</TableCell><TableCell>Next Review</TableCell></TableRow></TableHead><TableBody>{controls.map((control) => <TableRow key={control.id} hover><TableCell>{control.controlId}</TableCell><TableCell>{control.title}</TableCell><TableCell>{control.status}</TableCell><TableCell>{control.owner || 'Unassigned'}</TableCell><TableCell>{control.nextReviewAt ? new Date(control.nextReviewAt).toLocaleDateString() : 'Not set'}</TableCell></TableRow>)}</TableBody></Table></Card></>;
}
