import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  CircularProgress,
  Divider,
  Grid,
  IconButton,
  LinearProgress,
  Stack,
  Tab,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Tabs,
  Tooltip,
  Typography
} from '@mui/material';
import RefreshIcon from '@mui/icons-material/Refresh';
import DownloadIcon from '@mui/icons-material/Download';
import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import SecurityIcon from '@mui/icons-material/Security';
import BugReportIcon from '@mui/icons-material/BugReport';
import WarningAmberIcon from '@mui/icons-material/WarningAmber';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import BuildIcon from '@mui/icons-material/Build';
import SpeedIcon from '@mui/icons-material/Speed';
import DescriptionIcon from '@mui/icons-material/Description';
import AssessmentIcon from '@mui/icons-material/Assessment';

import StatusChip from '../components/StatusChip';
import { reportApi } from '../services/api';
import { RiskReportRecord } from '../data/reports';
import { VulnerabilitySeverity } from '../data/vulnerabilities';
import { RiskLevel } from '../data/risk';

const severityColors: Record<VulnerabilitySeverity, string> = {
  CRITICAL: '#EF4444',
  HIGH: '#F59E0B',
  MEDIUM: '#38BDF8',
  LOW: '#22C55E'
};

const riskLevelColors: Record<RiskLevel, string> = {
  CRITICAL: '#EF4444',
  HIGH: '#F59E0B',
  MEDIUM: '#38BDF8',
  LOW: '#22C55E'
};

export default function ReportsPage() {
  const navigate = useNavigate();

  const [report, setReport] = useState<RiskReportRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState(0);
  const [downloading, setDownloading] = useState(false);

  const loadReport = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await reportApi.getCurrentReport();
      setReport(response.data);
    } catch (err: any) {
      console.error('Failed to load risk report:', err);
      const msg = err.response?.data?.message || err.message || 'Failed to load enterprise risk report.';
      setError(msg);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReport();
  }, []);

  const handleDownload = async (format: 'markdown' | 'json') => {
    if (!report) return;
    setDownloading(true);
    try {
      const response = await reportApi.exportReport(format);
      const blob = new Blob([response.data], {
        type: format === 'json' ? 'application/json' : 'text/markdown'
      });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      const extension = format === 'json' ? 'json' : 'md';
      link.setAttribute('download', `risk-report-${new Date().toISOString().slice(0, 10)}.${extension}`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err: any) {
      console.error('Download failed:', err);
      alert('Failed to download report. Please try again.');
    } finally {
      setDownloading(false);
    }
  };

  const csvValue = (value: unknown) => {
    const text = value === undefined || value === null ? '' : String(value);
    return `"${text.replace(/"/g, '""')}"`;
  };

  const handleDownloadCsv = () => {
    if (!report) return;

    const rows: unknown[][] = [
      ['Report Summary', 'Value'],
      ['Report ID', report.reportId],
      ['Generated At', report.generatedAt],
      ['Generated By', report.generatedBy],
      ['Scope', report.scope],
      ['Overall Risk Score', report.overallRiskScore],
      ['Overall Risk Category', report.overallRiskCategory],
      ['Total Assets Assessed', report.totalAssetsAssessed],
      ['Total Vulnerabilities', report.totalVulnerabilities],
      ['Open Vulnerabilities', report.openVulnerabilities],
      ['Patched Vulnerabilities', report.patchedVulnerabilities],
      ['Pending Patches', report.pendingPatches],
      ['Critical Vulnerabilities', report.criticalVulnerabilities],
      ['High Vulnerabilities', report.highVulnerabilities],
      ['Medium Vulnerabilities', report.mediumVulnerabilities],
      ['Low Vulnerabilities', report.lowVulnerabilities],
      ['Highest CVSS Score', report.highestCvssScore ?? ''],
      ['Average CVSS Score', report.averageCvssScore ?? ''],
      [],
      ['Highest-Risk Assets'],
      ['Asset ID', 'Asset Identifier', 'Asset Name', 'Environment', 'Risk Score', 'Risk Category', 'Open Vulnerabilities', 'Highest CVSS Score'],
      ...report.highestRiskAssets.map((asset) => [
        asset.assetId,
        asset.assetIdentifier,
        asset.assetName,
        asset.environment,
        asset.riskScore,
        asset.riskCategory,
        asset.openVulnerabilityCount,
        asset.highestCvssScore ?? ''
      ]),
      [],
      ['Pending Remediations'],
      ['Vulnerability ID', 'Asset', 'Vulnerability', 'Severity', 'Patch Status', 'Affected Component', 'Due Date', 'Assignee', 'Patch Version'],
      ...report.pendingRemediations.map((item) => [
        item.vulnerabilityId,
        item.assetName,
        item.title,
        item.severity,
        item.patchStatus || 'OPEN',
        item.affectedComponent,
        item.dueDate ?? '',
        item.assignedRemediationOwner ?? '',
        item.patchVersion ?? ''
      ]),
      [],
      ['CVE Catalog'],
      ['CVE ID', 'CVSS Score', 'Severity', 'Affected Software', 'Affected Version', 'Description', 'Remediation'],
      ...report.cveRecords.map((cve) => [
        cve.cveId,
        cve.cvssScore,
        cve.severity,
        cve.affectedSoftware,
        cve.affectedVersion ?? '',
        cve.description,
        cve.remediation ?? ''
      ])
    ];

    const csv = rows.map((row) => row.map(csvValue).join(',')).join('\r\n');
    const blob = new Blob([`\uFEFF${csv}`], { type: 'text/csv;charset=utf-8' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `risk-report-${new Date().toISOString().slice(0, 10)}.csv`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  };

  const overallScore = report ? Number(report.overallRiskScore) || 0 : 0;
  const overallCategory = report ? report.overallRiskCategory : 'LOW';
  const categoryColor = riskLevelColors[overallCategory] || '#22C55E';

  return (
    <Box sx={{ width: '100%' }}>
      {/* Header */}
      <Stack
        direction={{ xs: 'column', md: 'row' }}
        justifyContent="space-between"
        alignItems={{ xs: 'flex-start', md: 'center' }}
        spacing={2}
        sx={{ mb: 4 }}
      >
        <Box>
          <Typography variant="h4" sx={{ fontWeight: 700, color: '#F8FAFC' }}>
            Enterprise Risk & Compliance Reports
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Generated security risk assessments, multi-vector vulnerability posture, patch remediation tracking, and audit reports
          </Typography>
        </Box>

        <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} alignItems="center">
          <Button
            variant="outlined"
            startIcon={<DownloadIcon />}
            onClick={() => handleDownload('markdown')}
            disabled={loading || !report || downloading}
            sx={{
              borderColor: '#334155',
              color: '#F8FAFC',
              textTransform: 'none',
              fontWeight: 600,
              '&:hover': { borderColor: '#8B5CF6', bgcolor: 'rgba(139, 92, 246, 0.05)' }
            }}
          >
            Export Markdown
          </Button>

          <Button
            variant="outlined"
            startIcon={<DownloadIcon />}
            onClick={() => handleDownload('json')}
            disabled={loading || !report || downloading}
            sx={{
              borderColor: '#334155',
              color: '#F8FAFC',
              textTransform: 'none',
              fontWeight: 600,
              '&:hover': { borderColor: '#8B5CF6', bgcolor: 'rgba(139, 92, 246, 0.05)' }
            }}
          >
            Export JSON
          </Button>

          <Button
            variant="outlined"
            startIcon={<DownloadIcon />}
            onClick={handleDownloadCsv}
            disabled={loading || !report || downloading}
            sx={{
              borderColor: '#334155',
              color: '#F8FAFC',
              textTransform: 'none',
              fontWeight: 600,
              '&:hover': { borderColor: '#22C55E', bgcolor: 'rgba(34, 197, 94, 0.05)' }
            }}
          >
            Export CSV
          </Button>

          <Button
            variant="contained"
            startIcon={<RefreshIcon />}
            onClick={loadReport}
            disabled={loading}
            sx={{
              background: 'linear-gradient(135deg, #7C3AED 0%, #6D28D9 100%)',
              color: '#FFFFFF',
              fontWeight: 600,
              textTransform: 'none',
              px: 2.5,
              py: 1,
              borderRadius: 2,
              '&:hover': {
                background: 'linear-gradient(135deg, #6D28D9 0%, #5B21B6 100%)',
              }
            }}
          >
            Generate Report
          </Button>
        </Stack>
      </Stack>

      {error && (
        <Alert
          severity="error"
          action={
            <Button color="inherit" size="small" onClick={loadReport}>
              Retry
            </Button>
          }
          sx={{ mb: 3 }}
        >
          {error}
        </Alert>
      )}

      {loading ? (
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', py: 12 }}>
          <CircularProgress size={48} sx={{ color: '#8B5CF6', mb: 2 }} />
          <Typography variant="body1" color="text.secondary">
            Generating enterprise security risk report...
          </Typography>
        </Box>
      ) : !report ? (
        <Card sx={{ background: '#151C2C', border: '1px solid #334155', borderRadius: 2, p: 4, textAlign: 'center' }}>
          <DescriptionIcon sx={{ fontSize: 48, color: '#64748B', mb: 1 }} />
          <Typography variant="h6" color="#F8FAFC" sx={{ mb: 1 }}>
            No Risk Report Data Available
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            Register infrastructure assets and run vulnerability scans to generate a comprehensive risk posture report.
          </Typography>
          <Button variant="contained" onClick={loadReport} sx={{ bgcolor: '#7C3AED' }}>
            Generate Report Now
          </Button>
        </Card>
      ) : (
        <Stack spacing={3}>
          {/* Metadata & Executive Summary Card */}
          <Card sx={{ background: '#151C2C', border: `1px solid ${categoryColor}40`, borderRadius: 2, position: 'relative', overflow: 'hidden' }}>
            <Box sx={{ position: 'absolute', top: 0, left: 0, right: 0, height: 4, bgcolor: categoryColor }} />
            <CardContent sx={{ p: { xs: 2.5, md: 3.5 } }}>
              <Grid container spacing={3} alignItems="center">
                {/* Executive Score Box */}
                <Grid item xs={12} md={3.5} sx={{ borderRight: { md: '1px solid #334155' }, pr: { md: 3 } }}>
                  <Stack spacing={1}>
                    <Typography variant="caption" sx={{ color: '#94A3B8', fontWeight: 600, textTransform: 'uppercase', letterSpacing: 0.5 }}>
                      Enterprise Risk Posture
                    </Typography>
                    <Stack direction="row" alignItems="baseline" spacing={1}>
                      <Typography variant="h2" sx={{ fontWeight: 800, color: categoryColor, letterSpacing: '-1px' }}>
                        {overallScore.toFixed(1)}
                      </Typography>
                      <Typography variant="h6" sx={{ color: '#64748B' }}>/ 100</Typography>
                    </Stack>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                      <Box
                        sx={{
                          px: 1.5,
                          py: 0.5,
                          borderRadius: 1,
                          fontWeight: 700,
                          fontSize: '0.8125rem',
                          bgcolor: `${categoryColor}20`,
                          color: categoryColor,
                          border: `1px solid ${categoryColor}60`
                        }}
                      >
                        {overallCategory} RISK TIER
                      </Box>
                      <Typography variant="caption" sx={{ color: '#94A3B8' }}>
                        {report.totalAssetsAssessed} Assets Assessed
                      </Typography>
                    </Box>
                  </Stack>
                </Grid>

                {/* Narrative Summary & Metadata */}
                <Grid item xs={12} md={8.5} sx={{ pl: { md: 2 } }}>
                  <Typography variant="h6" sx={{ fontWeight: 600, color: '#F8FAFC', mb: 1 }}>
                    Executive Summary
                  </Typography>
                  <Typography variant="body1" sx={{ color: '#CBD5E1', lineHeight: 1.6, mb: 2 }}>
                    {report.executiveSummary}
                  </Typography>
                  <Divider sx={{ borderColor: '#1E293B', mb: 1.5 }} />
                  <Grid container spacing={2}>
                    <Grid item xs={12} sm={4}>
                      <Typography variant="caption" sx={{ color: '#64748B', display: 'block' }}>REPORT ID</Typography>
                      <Typography variant="body2" sx={{ color: '#94A3B8', fontFamily: 'monospace', fontSize: '0.75rem' }}>
                        {report.reportId}
                      </Typography>
                    </Grid>
                    <Grid item xs={12} sm={4}>
                      <Typography variant="caption" sx={{ color: '#64748B', display: 'block' }}>GENERATED AT</Typography>
                      <Typography variant="body2" sx={{ color: '#94A3B8' }}>
                        {new Date(report.generatedAt).toLocaleString()}
                      </Typography>
                    </Grid>
                    <Grid item xs={12} sm={4}>
                      <Typography variant="caption" sx={{ color: '#64748B', display: 'block' }}>GENERATED BY</Typography>
                      <Typography variant="body2" sx={{ color: '#94A3B8' }}>
                        {report.generatedBy}
                      </Typography>
                    </Grid>
                  </Grid>
                </Grid>
              </Grid>
            </CardContent>
          </Card>

          {/* KPI Summary Cards Grid (7 Cards) */}
          <Grid container spacing={2}>
            {/* Total Vulns */}
            <Grid item xs={12} sm={6} md={3} lg={1.71}>
              <Card sx={{ background: '#151C2C', border: '1px solid #334155', borderRadius: 2, height: '100%' }}>
                <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                  <Stack spacing={0.5}>
                    <Stack direction="row" justifyContent="space-between" alignItems="center">
                      <Typography variant="caption" sx={{ color: '#A7B0C0', fontWeight: 600, textTransform: 'uppercase' }}>
                        Total Vulns
                      </Typography>
                      <BugReportIcon sx={{ color: '#38BDF8', fontSize: 18 }} />
                    </Stack>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#F8FAFC' }}>
                      {report.totalVulnerabilities}
                    </Typography>
                    <Typography variant="caption" sx={{ color: '#64748B' }}>
                      Across {report.totalAssetsAssessed} asset(s)
                    </Typography>
                  </Stack>
                </CardContent>
              </Card>
            </Grid>

            {/* Critical Vulns */}
            <Grid item xs={12} sm={6} md={3} lg={1.71}>
              <Card sx={{ background: '#151C2C', border: '1px solid rgba(239, 68, 68, 0.4)', borderRadius: 2, height: '100%' }}>
                <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                  <Stack spacing={0.5}>
                    <Stack direction="row" justifyContent="space-between" alignItems="center">
                      <Typography variant="caption" sx={{ color: '#EF4444', fontWeight: 600, textTransform: 'uppercase' }}>
                        Critical
                      </Typography>
                      <WarningAmberIcon sx={{ color: '#EF4444', fontSize: 18 }} />
                    </Stack>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#EF4444' }}>
                      {report.criticalVulnerabilities}
                    </Typography>
                    <Typography variant="caption" sx={{ color: '#EF4444', opacity: 0.8 }}>
                      Immediate action required
                    </Typography>
                  </Stack>
                </CardContent>
              </Card>
            </Grid>

            {/* High Vulns */}
            <Grid item xs={12} sm={6} md={3} lg={1.71}>
              <Card sx={{ background: '#151C2C', border: '1px solid rgba(245, 158, 11, 0.4)', borderRadius: 2, height: '100%' }}>
                <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                  <Stack spacing={0.5}>
                    <Stack direction="row" justifyContent="space-between" alignItems="center">
                      <Typography variant="caption" sx={{ color: '#F59E0B', fontWeight: 600, textTransform: 'uppercase' }}>
                        High Severity
                      </Typography>
                      <WarningAmberIcon sx={{ color: '#F59E0B', fontSize: 18 }} />
                    </Stack>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#F59E0B' }}>
                      {report.highVulnerabilities}
                    </Typography>
                    <Typography variant="caption" sx={{ color: '#F59E0B', opacity: 0.8 }}>
                      Elevated risk exposure
                    </Typography>
                  </Stack>
                </CardContent>
              </Card>
            </Grid>

            {/* Open Vulns */}
            <Grid item xs={12} sm={6} md={3} lg={1.71}>
              <Card sx={{ background: '#151C2C', border: '1px solid #334155', borderRadius: 2, height: '100%' }}>
                <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                  <Stack spacing={0.5}>
                    <Stack direction="row" justifyContent="space-between" alignItems="center">
                      <Typography variant="caption" sx={{ color: '#A7B0C0', fontWeight: 600, textTransform: 'uppercase' }}>
                        Active Open
                      </Typography>
                      <SecurityIcon sx={{ color: '#8B5CF6', fontSize: 18 }} />
                    </Stack>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#F8FAFC' }}>
                      {report.openVulnerabilities}
                    </Typography>
                    <Typography variant="caption" sx={{ color: '#64748B' }}>
                      Unremediated issues
                    </Typography>
                  </Stack>
                </CardContent>
              </Card>
            </Grid>

            {/* Patched */}
            <Grid item xs={12} sm={6} md={3} lg={1.71}>
              <Card sx={{ background: '#151C2C', border: '1px solid rgba(34, 197, 94, 0.4)', borderRadius: 2, height: '100%' }}>
                <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                  <Stack spacing={0.5}>
                    <Stack direction="row" justifyContent="space-between" alignItems="center">
                      <Typography variant="caption" sx={{ color: '#22C55E', fontWeight: 600, textTransform: 'uppercase' }}>
                        Patched
                      </Typography>
                      <CheckCircleIcon sx={{ color: '#22C55E', fontSize: 18 }} />
                    </Stack>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#22C55E' }}>
                      {report.patchedVulnerabilities}
                    </Typography>
                    <Typography variant="caption" sx={{ color: '#22C55E', opacity: 0.8 }}>
                      Resolved & verified
                    </Typography>
                  </Stack>
                </CardContent>
              </Card>
            </Grid>

            {/* Pending Patches */}
            <Grid item xs={12} sm={6} md={3} lg={1.71}>
              <Card sx={{ background: '#151C2C', border: '1px solid #334155', borderRadius: 2, height: '100%' }}>
                <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                  <Stack spacing={0.5}>
                    <Stack direction="row" justifyContent="space-between" alignItems="center">
                      <Typography variant="caption" sx={{ color: '#A7B0C0', fontWeight: 600, textTransform: 'uppercase' }}>
                        Pending Patches
                      </Typography>
                      <BuildIcon sx={{ color: '#F59E0B', fontSize: 18 }} />
                    </Stack>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#F8FAFC' }}>
                      {report.pendingPatches}
                    </Typography>
                    <Typography variant="caption" sx={{ color: '#64748B' }}>
                      In remediation pipeline
                    </Typography>
                  </Stack>
                </CardContent>
              </Card>
            </Grid>

            {/* Highest CVSS */}
            <Grid item xs={12} sm={6} md={3} lg={1.74}>
              <Card sx={{ background: '#151C2C', border: '1px solid #38BDF8', borderRadius: 2, height: '100%' }}>
                <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                  <Stack spacing={0.5}>
                    <Stack direction="row" justifyContent="space-between" alignItems="center">
                      <Typography variant="caption" sx={{ color: '#38BDF8', fontWeight: 600, textTransform: 'uppercase' }}>
                        Highest CVSS
                      </Typography>
                      <SpeedIcon sx={{ color: '#38BDF8', fontSize: 18 }} />
                    </Stack>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#38BDF8' }}>
                      {report.highestCvssScore !== undefined && report.highestCvssScore !== null ? Number(report.highestCvssScore).toFixed(1) : 'N/A'}
                    </Typography>
                    <Typography variant="caption" sx={{ color: '#64748B' }}>
                      Avg: {report.averageCvssScore !== undefined && report.averageCvssScore !== null ? Number(report.averageCvssScore).toFixed(1) : 'N/A'}
                    </Typography>
                  </Stack>
                </CardContent>
              </Card>
            </Grid>
          </Grid>

          {/* Tabbed Report Details */}
          <Card sx={{ background: '#151C2C', border: '1px solid #334155', borderRadius: 2 }}>
            <Box sx={{ borderBottom: '1px solid #1E293B', px: 2 }}>
              <Tabs
                value={activeTab}
                onChange={(_, newValue) => setActiveTab(newValue)}
                sx={{
                  '& .MuiTab-root': {
                    color: '#94A3B8',
                    textTransform: 'none',
                    fontWeight: 600,
                    fontSize: '0.875rem',
                    py: 2,
                    '&.Mui-selected': { color: '#8B5CF6' }
                  },
                  '& .MuiTabs-indicator': { backgroundColor: '#8B5CF6', height: 3 }
                }}
              >
                <Tab label={`Highest-Risk Assets (${report.highestRiskAssets.length})`} />
                <Tab label={`Pending Remediations (${report.pendingRemediations.length})`} />
                <Tab label={`CVE Catalog (${report.cveRecords.length})`} />
                <Tab label={`Integrations (SonarQube: ${report.sonarQubeFindings.length} / Trivy: ${report.trivyFindingsCount})`} />
              </Tabs>
            </Box>

            <CardContent sx={{ p: 3 }}>
              {/* TAB 0: Highest-Risk Assets */}
              {activeTab === 0 && (
                <TableContainer sx={{ borderRadius: 1.5, border: '1px solid #1E293B', bgcolor: '#0B1020' }}>
                  <Table>
                    <TableHead sx={{ bgcolor: '#151C2C' }}>
                      <TableRow>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Asset</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Environment</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Risk Score</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Risk Tier</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }} align="center">Open Vulns</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }} align="center">Highest CVSS</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }} align="right">Action</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {report.highestRiskAssets.length === 0 ? (
                        <TableRow>
                          <TableCell colSpan={7} sx={{ textAlign: 'center', py: 5, color: '#64748B' }}>
                            No assessed assets found
                          </TableCell>
                        </TableRow>
                      ) : (
                        report.highestRiskAssets.map((asset) => {
                          const score = Number(asset.riskScore) || 0;
                          const color = riskLevelColors[asset.riskCategory] || '#22C55E';
                          return (
                            <TableRow key={asset.assetId} hover sx={{ borderBottom: '1px solid #1E293B' }}>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography
                                  variant="body2"
                                  sx={{
                                    fontWeight: 600,
                                    color: '#F8FAFC',
                                    cursor: 'pointer',
                                    '&:hover': { color: '#8B5CF6', textDecoration: 'underline' }
                                  }}
                                  onClick={() => navigate(`/assets/${asset.assetId}`)}
                                >
                                  {asset.assetName}
                                </Typography>
                                <Typography variant="caption" sx={{ color: '#64748B' }}>
                                  {asset.assetIdentifier}
                                </Typography>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <StatusChip
                                  label={asset.environment || 'UNKNOWN'}
                                  severity={
                                    asset.environment === 'PRODUCTION'
                                      ? 'error'
                                      : asset.environment === 'STAGING'
                                      ? 'warning'
                                      : 'info'
                                  }
                                />
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Box sx={{ width: 130 }}>
                                  <Stack direction="row" justifyContent="space-between" sx={{ mb: 0.5 }}>
                                    <Typography variant="body2" sx={{ fontWeight: 700, color }}>
                                      {score.toFixed(1)}
                                    </Typography>
                                    <Typography variant="caption" sx={{ color: '#64748B' }}>/ 100</Typography>
                                  </Stack>
                                  <LinearProgress
                                    variant="determinate"
                                    value={Math.min(score, 100)}
                                    sx={{
                                      height: 6,
                                      borderRadius: 3,
                                      bgcolor: '#1E293B',
                                      '& .MuiLinearProgress-bar': { bgcolor: color, borderRadius: 3 }
                                    }}
                                  />
                                </Box>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Box
                                  sx={{
                                    display: 'inline-block',
                                    px: 1.2,
                                    py: 0.3,
                                    borderRadius: 1,
                                    fontWeight: 600,
                                    fontSize: '0.75rem',
                                    bgcolor: `${color}1A`,
                                    color,
                                    border: `1px solid ${color}4D`
                                  }}
                                >
                                  {asset.riskCategory}
                                </Box>
                              </TableCell>
                              <TableCell align="center" sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography variant="body2" sx={{ fontWeight: 700, color: asset.openVulnerabilityCount > 0 ? '#EF4444' : '#22C55E' }}>
                                  {asset.openVulnerabilityCount}
                                </Typography>
                              </TableCell>
                              <TableCell align="center" sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography variant="body2" sx={{ fontWeight: 600, color: '#38BDF8' }}>
                                  {asset.highestCvssScore !== undefined && asset.highestCvssScore !== null ? Number(asset.highestCvssScore).toFixed(1) : 'None'}
                                </Typography>
                              </TableCell>
                              <TableCell align="right" sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Tooltip title="View Asset Details">
                                  <IconButton
                                    size="small"
                                    onClick={() => navigate(`/assets/${asset.assetId}`)}
                                    sx={{ color: '#8B5CF6', bgcolor: 'rgba(139, 92, 246, 0.1)' }}
                                  >
                                    <OpenInNewIcon fontSize="small" />
                                  </IconButton>
                                </Tooltip>
                              </TableCell>
                            </TableRow>
                          );
                        })
                      )}
                    </TableBody>
                  </Table>
                </TableContainer>
              )}

              {/* TAB 1: Pending Remediations */}
              {activeTab === 1 && (
                <TableContainer sx={{ borderRadius: 1.5, border: '1px solid #1E293B', bgcolor: '#0B1020' }}>
                  <Table>
                    <TableHead sx={{ bgcolor: '#151C2C' }}>
                      <TableRow>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Vulnerability</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Asset</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Severity</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Patch Status</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Remediation Guidance</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Due Date</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Assignee</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {report.pendingRemediations.length === 0 ? (
                        <TableRow>
                          <TableCell colSpan={7} sx={{ textAlign: 'center', py: 5, color: '#22C55E' }}>
                            <CheckCircleIcon sx={{ fontSize: 32, mb: 1, display: 'block', mx: 'auto' }} />
                            All vulnerabilities have been remediated or verified!
                          </TableCell>
                        </TableRow>
                      ) : (
                        report.pendingRemediations.map((item) => {
                          const sevColor = severityColors[item.severity] || '#38BDF8';
                          return (
                            <TableRow key={item.vulnerabilityId} hover sx={{ borderBottom: '1px solid #1E293B' }}>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography variant="body2" sx={{ fontWeight: 600, color: '#F8FAFC' }}>
                                  {item.title}
                                </Typography>
                                <Typography variant="caption" sx={{ color: '#64748B' }}>
                                  {item.vulnerabilityIdentifier} {item.affectedComponent ? `• ${item.affectedComponent}` : ''}
                                </Typography>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography
                                  variant="body2"
                                  sx={{ color: '#38BDF8', cursor: 'pointer', '&:hover': { textDecoration: 'underline' } }}
                                  onClick={() => navigate(`/assets/${item.assetId}`)}
                                >
                                  {item.assetName}
                                </Typography>
                                <Typography variant="caption" sx={{ color: '#64748B' }}>
                                  {item.assetIdentifier}
                                </Typography>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Box
                                  sx={{
                                    display: 'inline-block',
                                    px: 1.2,
                                    py: 0.3,
                                    borderRadius: 1,
                                    fontWeight: 700,
                                    fontSize: '0.75rem',
                                    bgcolor: `${sevColor}1A`,
                                    color: sevColor,
                                    border: `1px solid ${sevColor}4D`
                                  }}
                                >
                                  {item.severity}
                                </Box>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <StatusChip
                                  label={item.patchStatus || 'OPEN'}
                                  severity={
                                    item.patchStatus === 'VERIFIED'
                                      ? 'success'
                                      : item.patchStatus === 'PATCHED'
                                      ? 'info'
                                      : item.patchStatus === 'PATCHING'
                                      ? 'warning'
                                      : 'error'
                                  }
                                />
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B', maxWidth: 280 }}>
                                <Typography variant="body2" sx={{ color: '#CBD5E1', fontSize: '0.8125rem' }}>
                                  {item.remediation || 'Apply latest vendor security patches.'}
                                </Typography>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography variant="caption" sx={{ color: '#94A3B8' }}>
                                  {item.dueDate ? new Date(item.dueDate).toLocaleDateString() : 'Not set'}
                                </Typography>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography variant="caption" sx={{ color: '#94A3B8' }}>
                                  {item.assignedRemediationOwner || 'Unassigned'}
                                </Typography>
                              </TableCell>
                            </TableRow>
                          );
                        })
                      )}
                    </TableBody>
                  </Table>
                </TableContainer>
              )}

              {/* TAB 2: CVE Catalog */}
              {activeTab === 2 && (
                <TableContainer sx={{ borderRadius: 1.5, border: '1px solid #1E293B', bgcolor: '#0B1020' }}>
                  <Table>
                    <TableHead sx={{ bgcolor: '#151C2C' }}>
                      <TableRow>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>CVE ID</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>CVSS Score</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Severity</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Affected Component</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Description</TableCell>
                        <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Remediation</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {report.cveRecords.length === 0 ? (
                        <TableRow>
                          <TableCell colSpan={6} sx={{ textAlign: 'center', py: 5, color: '#64748B' }}>
                            No registered CVE records found
                          </TableCell>
                        </TableRow>
                      ) : (
                        report.cveRecords.map((cve) => {
                          const sevColor = severityColors[cve.severity] || '#38BDF8';
                          return (
                            <TableRow key={cve.id} hover sx={{ borderBottom: '1px solid #1E293B' }}>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography variant="body2" sx={{ fontWeight: 700, color: '#F8FAFC' }}>
                                  {cve.cveId}
                                </Typography>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography variant="body2" sx={{ fontWeight: 700, color: Number(cve.cvssScore) >= 9.0 ? '#EF4444' : Number(cve.cvssScore) >= 7.0 ? '#F59E0B' : '#38BDF8' }}>
                                  {cve.cvssScore !== undefined && cve.cvssScore !== null ? Number(cve.cvssScore).toFixed(1) : 'N/A'}
                                </Typography>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Box
                                  sx={{
                                    display: 'inline-block',
                                    px: 1.2,
                                    py: 0.3,
                                    borderRadius: 1,
                                    fontWeight: 700,
                                    fontSize: '0.75rem',
                                    bgcolor: `${sevColor}1A`,
                                    color: sevColor,
                                    border: `1px solid ${sevColor}4D`
                                  }}
                                >
                                  {cve.severity}
                                </Box>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                <Typography variant="body2" sx={{ color: '#CBD5E1' }}>
                                  {cve.affectedSoftware} {cve.affectedVersion ? `(${cve.affectedVersion})` : ''}
                                </Typography>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B', maxWidth: 320 }}>
                                <Typography variant="body2" sx={{ color: '#94A3B8', fontSize: '0.8125rem' }}>
                                  {cve.description}
                                </Typography>
                              </TableCell>
                              <TableCell sx={{ borderBottom: '1px solid #1E293B', maxWidth: 220 }}>
                                <Typography variant="body2" sx={{ color: '#CBD5E1', fontSize: '0.8125rem' }}>
                                  {cve.remediation || 'Upgrade to latest release.'}
                                </Typography>
                              </TableCell>
                            </TableRow>
                          );
                        })
                      )}
                    </TableBody>
                  </Table>
                </TableContainer>
              )}

              {/* TAB 3: Integrations */}
              {activeTab === 3 && (
                <Stack spacing={3}>
                  <Box>
                    <Typography variant="h6" sx={{ fontWeight: 600, color: '#F8FAFC', mb: 1.5 }}>
                      SonarQube Security Issues ({report.sonarQubeFindings.length})
                    </Typography>
                    <TableContainer sx={{ borderRadius: 1.5, border: '1px solid #1E293B', bgcolor: '#0B1020' }}>
                      <Table>
                        <TableHead sx={{ bgcolor: '#151C2C' }}>
                          <TableRow>
                            <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Issue Key</TableCell>
                            <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Rule</TableCell>
                            <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Severity</TableCell>
                            <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Component & Line</TableCell>
                            <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Message</TableCell>
                            <TableCell sx={{ color: '#94A3B8', fontWeight: 600, borderBottom: '1px solid #1E293B' }}>Status</TableCell>
                          </TableRow>
                        </TableHead>
                        <TableBody>
                          {report.sonarQubeFindings.length === 0 ? (
                            <TableRow>
                              <TableCell colSpan={6} sx={{ textAlign: 'center', py: 4, color: '#64748B' }}>
                                No SonarQube findings imported
                              </TableCell>
                            </TableRow>
                          ) : (
                            report.sonarQubeFindings.map((sq) => {
                              const sevColor = severityColors[sq.severity] || '#38BDF8';
                              return (
                                <TableRow key={sq.id} hover sx={{ borderBottom: '1px solid #1E293B' }}>
                                  <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                    <Typography variant="body2" sx={{ fontWeight: 600, color: '#F8FAFC' }}>
                                      {sq.issueKey}
                                    </Typography>
                                    <Typography variant="caption" sx={{ color: '#64748B' }}>
                                      {sq.projectKey}
                                    </Typography>
                                  </TableCell>
                                  <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                    <Typography variant="body2" sx={{ fontFamily: 'monospace', color: '#CBD5E1', fontSize: '0.8125rem' }}>
                                      {sq.rule}
                                    </Typography>
                                  </TableCell>
                                  <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                    <Box
                                      sx={{
                                        display: 'inline-block',
                                        px: 1.2,
                                        py: 0.3,
                                        borderRadius: 1,
                                        fontWeight: 700,
                                        fontSize: '0.75rem',
                                        bgcolor: `${sevColor}1A`,
                                        color: sevColor,
                                        border: `1px solid ${sevColor}4D`
                                      }}
                                    >
                                      {sq.severity}
                                    </Box>
                                  </TableCell>
                                  <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                    <Typography variant="body2" sx={{ color: '#CBD5E1' }}>
                                      {sq.component} {sq.lineNumber ? `(L${sq.lineNumber})` : ''}
                                    </Typography>
                                  </TableCell>
                                  <TableCell sx={{ borderBottom: '1px solid #1E293B', maxWidth: 300 }}>
                                    <Typography variant="body2" sx={{ color: '#94A3B8', fontSize: '0.8125rem' }}>
                                      {sq.message}
                                    </Typography>
                                  </TableCell>
                                  <TableCell sx={{ borderBottom: '1px solid #1E293B' }}>
                                    <StatusChip label={sq.status} severity={sq.status === 'RESOLVED' ? 'success' : 'warning'} />
                                  </TableCell>
                                </TableRow>
                              );
                            })
                          )}
                        </TableBody>
                      </Table>
                    </TableContainer>
                  </Box>

                  <Box>
                    <Typography variant="h6" sx={{ fontWeight: 600, color: '#F8FAFC', mb: 1.5 }}>
                      Trivy Container Scan Finding Summary
                    </Typography>
                    <Card sx={{ background: '#0B1020', border: '1px solid #1E293B', p: 2.5, borderRadius: 1.5 }}>
                      <Stack direction="row" spacing={3} alignItems="center">
                        <Box sx={{ p: 1.5, bgcolor: 'rgba(56, 189, 248, 0.1)', borderRadius: 2 }}>
                          <SecurityIcon sx={{ fontSize: 32, color: '#38BDF8' }} />
                        </Box>
                        <Box>
                          <Typography variant="body1" sx={{ fontWeight: 600, color: '#F8FAFC' }}>
                            {report.trivyFindingsCount} Container Scan Finding(s) Ingestion Active
                          </Typography>
                          <Typography variant="caption" color="text.secondary">
                            Vulnerabilities identified by container and OS package image scanners are unified into the risk scoring pipeline.
                          </Typography>
                        </Box>
                      </Stack>
                    </Card>
                  </Box>
                </Stack>
              )}
            </CardContent>
          </Card>
        </Stack>
      )}
    </Box>
  );
}
