import { useEffect, useState } from 'react';
import { Alert, Button, Card, Dialog, DialogActions, DialogContent, DialogTitle, Grid, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import FactCheckIcon from '@mui/icons-material/FactCheck';
import PendingActionsIcon from '@mui/icons-material/PendingActions';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import PageHeader from '../components/PageHeader';
import { securityReviewApi } from '../services/api';
import AccentMetricCard from '../components/AccentMetricCard';

export default function SecurityReviewsPage() {
  const [reviews, setReviews] = useState<any[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState<string | null>(null); const [form, setForm] = useState({ scope: '', reviewPeriod: '', findings: '', anomalies: '', comments: '' });
  const load = () => securityReviewApi.getReviews().then((r) => setReviews(r.data)).catch((e) => setError(e.response?.data?.message || e.message)); useEffect(() => { load(); }, []);
  const create = async () => { try { await securityReviewApi.createReview(form); setOpen(false); setForm({ scope: '', reviewPeriod: '', findings: '', anomalies: '', comments: '' }); load(); } catch (e: any) { setError(e.response?.data?.message || e.message); } };
  return <><PageHeader title="Security Reviews" subtitle="Review findings, anomalies, approvals, and audit actions" /><Button startIcon={<AddIcon />} variant="contained" onClick={() => setOpen(true)} sx={{ mb: 3 }}>New Review</Button>{error && <Alert severity="error">{error}</Alert>}<Grid container spacing={2} sx={{ mb: 3 }}><Grid item xs={12} sm={4}><AccentMetricCard label="Total Reviews" value={reviews.length} subtitle="Review register" color="#38BDF8" icon={<FactCheckIcon />} /></Grid><Grid item xs={12} sm={4}><AccentMetricCard label="Pending" value={reviews.filter((review) => review.status === 'PENDING' || review.status === 'IN_REVIEW').length} subtitle="Awaiting action" color="#F59E0B" icon={<PendingActionsIcon />} /></Grid><Grid item xs={12} sm={4}><AccentMetricCard label="Completed" value={reviews.filter((review) => review.status === 'COMPLETED' || review.status === 'APPROVED').length} subtitle="Approved or completed" color="#22C55E" icon={<CheckCircleIcon />} /></Grid></Grid><Card sx={{ overflow: 'hidden', borderColor: '#334155' }}><Table><TableHead><TableRow sx={{ bgcolor: '#101827' }}><TableCell>Scope</TableCell><TableCell>Period</TableCell><TableCell>Status</TableCell><TableCell>Reviewer</TableCell><TableCell>Review Date</TableCell></TableRow></TableHead><TableBody>{reviews.map((review) => <TableRow key={review.id} hover><TableCell>{review.scope}</TableCell><TableCell>{review.reviewPeriod}</TableCell><TableCell>{review.status}</TableCell><TableCell>{review.reviewer}</TableCell><TableCell>{review.reviewDate ? new Date(review.reviewDate).toLocaleString() : ''}</TableCell></TableRow>)}</TableBody></Table></Card><Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Create Security Review</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Scope" value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value })} /><TextField label="Review period" value={form.reviewPeriod} onChange={(e) => setForm({ ...form, reviewPeriod: e.target.value })} /><TextField label="Findings" multiline minRows={2} value={form.findings} onChange={(e) => setForm({ ...form, findings: e.target.value })} /><TextField label="Anomalies" multiline minRows={2} value={form.anomalies} onChange={(e) => setForm({ ...form, anomalies: e.target.value })} /><TextField label="Comments" multiline minRows={2} value={form.comments} onChange={(e) => setForm({ ...form, comments: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" onClick={create}>Create</Button></DialogActions></Dialog></>;
}
