spring.application.name=asset-service

spring.application.name=sentinelcore-auth

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinelcore
spring.datasource.username=postgres
spring.datasource.password=121006

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=change-this-to-a-long-random-secret-key-for-development
jwt.expiration=86400000